name: Blog自动部署 # 脚本 workflow 名称

on:
  push:
    branches: main  # 当监测 main,master 的 push
    paths: # 监测所有 source 目录下的文件变动，所有 yml,json 后缀文件的变动。
      - '*.json'
      - '**.yml'
      - '**/source/**'
env: # 设置全局变量
  NODE_VERSION: '22.x'
  
jobs:
  blog: # 任务名称
    timeout-minutes: 30 # 设置 30 分钟超时
    runs-on: ubuntu-latest # 指定最新 ubuntu 系统
    
    steps:
      - uses: actions/checkout@v4 # 拉取仓库代码
      
      - name: 设置node环境 ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4 # 设置 node.js 环境
        with: 
          node-version:  ${{ env.NODE_VERSION }}
          
      - name: 读取仓库环境变量HEXO_SSH_PUD
        run: |
          echo "仓库环境变量HEXO_SSH_PUD:${{env.NODE_VERSION}}"
          echo "仓库环境变量HEXO_SSH_PUD:${{vars.VARS_TEST}}"
          
      # 将ssh写入虚拟主机上
      - name: 将ssh写入虚拟主机.ssh文件夹上
        env:
          HEXO_DEPLOY_PRI: ${{vars.HEXO_SSH_PUD}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"  # 设置时区
          mkdir -p ~/.ssh/  
          # 使用 ssh-keyscan 命令将远程主机的公钥添加到 known_hosts 文件中
          echo "$HEXO_DEPLOY_PRI" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # 写入全局
          git config --global user.name "jinwei26" 
          git config --global user.email "195569807@qq.com"
          cat ~/.ssh/id_rsa



