name: Blog自动部署 # 脚本 workflow 名称

on:
  push:
    branches: main  # 当监测 main,master 的 push
    paths: # 监测所有 source 目录下的文件变动，所有 yml,json 后缀文件的变动。
      - '*.json'
      - '**.yml'
      - '**/source/**'
env: # 设置全局变量
  NODE_VERSION: '22.x'
  
jobs:
  blog: # 任务名称
    timeout-minutes: 30 # 设置 30 分钟超时
    runs-on: ubuntu-latest # 指定最新 ubuntu 系统
    
    steps:
      - uses: actions/checkout@v4 # 拉取仓库代码
      
      - name: 设置node环境 ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4 # 设置 node.js 环境
        with: 
          node-version:  ${{ env.NODE_VERSION }}
          cache: 'npm'  # 自动缓存 npm
          
      - name: 读取仓库环境变量HEXO_SSH_PUD
        run: |
          echo "仓库环境变量HEXO_SSH_PUD:${{secrets.HEXO_SSH_PUD}}

          echo "仓库环境变量HEXO_SSH_PUD:${{env.HEXO_SSH_PUD}}
